spring:
  application:
    name: backend-template
  datasource:
    hikari:
      maximum-pool-size: 10
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  profiles:
    default: dev
  flyway:
    baseline-on-migrate: true
    baseline-version: 1

security:
  jwt:
    expiration: 3600
